#!/bin/bash
file="/sys/class/backlight/intel_backlight/brightness"
val=$(cat "$file")
fileml="/sys/class/backlight/intel_backlight/max_brightness"
maxl=$(cat "$fileml")
if [ "$val" -lt "$maxl" ];then
     xbacklight -inc 10 

fi
