# fading
fading=false

# shadows
shadow = true
no-dock-shadow = false
no-dnd-shadow = false
clear-shadow = true

# misc
backend = "xrender"
glx-no-stencil = "xrender"
glx-copy-from-front = true
xrender-sync = true
xrender-sync-fence = true
vsync = true
