# Enable 256 color output
set -g default-terminal "screen-256color"
set-environment -g DISPLAY :0
# More responsive escape key
set -sg escape-time 0

#Unbind C-b and binding prefix to C-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

#Force a reload of config file
unbind r
bind r source-file ~/.tmux.conf

#Rebind of splitting keybind
unbind-key '"'  
bind-key C-v split-window
unbind-key '%'
bind-key C-h split-window -h

# Vi-like pane navigation
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-j select-pane -D
bind -n M-k select-pane -U
unbind Up
unbind Down
unbind Left
unbind Right

# Vi-like pane resizing
bind -n M-H resize-pane -L 5
bind -n M-L resize-pane -R 5
bind -n M-J resize-pane -D 5
bind -n M-K resize-pane -U 5

#vi-like normal mode

setw -g mode-keys vi
unbind [
bind Escape copy-mode
unbind p
bind p paste-buffer
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -in -selection clipboard"

#ssh host
set -g set-titles on
set -g set-titles-string "#T"
